# Generated by Django 3.2.20 on 2023-07-19 13:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('Gender', models.CharField(choices=[(0, ''), (1, 'FEMALE'), (2, 'MALE'), (3, 'OTHER')], default='', max_length=50)),
                ('referred', models.CharField(choices=[(0, ''), (1, 'NO'), (2, 'YES')], default='', max_length=50)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (1, 'PUBLISHED')], default=0)),
                ('patient_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('Gender', models.CharField(choices=[(0, ''), (1, 'FEMALE'), (2, 'MALE'), (3, 'OTHER')], default='', max_length=50)),
                ('referred', models.CharField(choices=[(0, ''), (1, 'NO'), (2, 'YES')], default='', max_length=50)),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('9 AM', '9 AM'), ('9:30 PM', '9:30 AM'), ('10 PM', '10 PM'), ('10:30 AM', '10:30 AM'), ('11 PM', '11 AM'), ('11:30 AM', '11:30 AM'), ('12 PM', '12 PM'), ('12:30 PM', '12:30 PM'), ('1 PM', '1 PM'), ('1:30 PM', '1:30 PM')], default='9 AM', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (1, 'PUBLISHED')], default=0)),
                ('patient_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
