# Generated by Django 3.2.20 on 2023-07-19 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['patient_ID']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_member',
            field=models.ForeignKey(choices=[(0, ''), (1, 'NO'), (2, 'YES')], default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='staff_member',
            field=models.ForeignKey(choices=[(0, ''), (1, 'NO'), (2, 'YES')], default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_ID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='patient_ID',
            field=models.CharField(default='', max_length=10),
        ),
    ]
