# Generated by Django 3.2.20 on 2023-07-21 10:32

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0005_auto_20230720_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_ID', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('full_name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('', ''), ('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('OTHER', 'OTHER')], default='', max_length=50)),
                ('appointment_number', models.CharField(choices=[('Inital Appointment', 'Inital Appointment'), ('Follow Up Appointment', 'Follow Up Appointment'), ('Final Results', 'Final Results')], default='', max_length=50)),
                ('appointment_notes', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, ''), (1, 'Just Recruited'), (2, 'Completed First Appointment'), (3, 'Completed Second Appointment')], default=0)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_number'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('', ''), ('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('OTHER', 'OTHER')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
