# Generated by Django 3.2.20 on 2023-07-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='slug',
        ),
    ]
